version: '3.8'

services:
  # Base service for unit tests (doesn't include Langflow)
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LANGFLOW: "false"
    volumes:
      - .:/app
    command: bash -c "source /activate-environment.sh && python -m pytest tests/unit -v"
    environment:
      - PYTHONPATH=/app
  
  # Service for integration tests (includes Langflow)
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LANGFLOW: "true"
    volumes:
      - .:/app
    command: bash -c "source /activate-environment.sh && python -m pytest tests/integration -v"
    environment:
      - PYTHONPATH=/app
      - LANGFLOW_AUTO_REGISTER_COMPONENTS=true
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
  
  # Development environment with Langflow
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LANGFLOW: "true"
    volumes:
      - .:/app
      - langflow_cache:/root/.cache/langflow  # Persist Langflow cache
    ports:
      - "7860:7860"  # Langflow UI port
    command: bash -c "source /activate-environment.sh && python -m langflow run --host 0.0.0.0 --port 7860"
    environment:
      - PYTHONPATH=/app
      - LANGFLOW_AUTO_REGISTER_COMPONENTS=true
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=9213633ece9ec43e5

volumes:
  langflow_cache:  # Named volume to persist Langflow cache between restarts
